version: '3.8'

services:
  backend:
    build:
      context: ./escalation-league-backend
    container_name: escalation-league-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./escalation-league-frontend
    container_name: escalation-league-frontend
    ports:
      - "8080:80"