services:
  card-db:
    image: mysql:8
    container_name: escalation-league-card-db
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${CARD_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CARD_DB_NAME}
      MYSQL_USER: ${CARD_DB_USER}
      MYSQL_PASSWORD: ${CARD_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - compose_card_db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${CARD_DB_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  compose_card_db_data:
    external: true
